### ISSUE TITLE
Change thumbs up / thumbs down

### ISSUE THREAD

**Issue by dmcwo** [UCLALibrary/uclalibrary.github.io#17]
Thanks for coming up with an alternative to the green/red dots for open and closed. I like what you have, but I'm worried that people will think the thumbs up/down have to do with ratings. I'm wondering if we can go with something simple like a rounded rectangle with the word "Open" inside (and another rounded rectangle with the words "Closed" inside). Let me know your thoughts.

**Comment by dmcwo** [comment]
Here's an idea:
http://thumb101.shutterstock.com/display_pic_with_logo/639229/113632117/stock-photo-open-around-the-clock-hours-a-day-icon-isolated-on-white-background-stylized-green-icon-113632117.jpg

**Comment by anumat** [comment]
Yup this would be great! Will implement this!

**Comment by anumat** [comment]
done!

**Comment by dmcwo** [comment]
Awesome! Looks great.
