### ISSUE TITLE
Add hamburger menu to top right

### ISSUE THREAD

**Issue by dmcwo** [UCLALibrary/uclalibrary.github.io#22]
Hi @anumat 

Add hamburger menu to top right with these links

Ask a Librarian - (will provide link)
My account - http://catalog.library.ucla.edu/vwebv/login
Research Guides - http://guides.library.ucla.edu
Search the UCLA Library Catalog - http://catalog.library.ucla.edu/

**Comment by anumat** [comment]
hey Doug, I added a hamburger menu. What do you think of it? (ask a librarian isn't done yet, I plan to work on it next.)

**Comment by dmcwo** [comment]
Looking good!! Once you're ready, can it appear on all pages?


Thank you! People are very pleased with your progress!


~~~
Doug Worsham
Teaching and Learning Services Coordinator
Interim Dir. Teaching and Learning Services
UCLA Library
dworsham@ucla.edu
310-206-7225
@dmcwo<http://twitter.com/dmcwo>


________________________________
From: Anumat Srivastava <notifications@github.com>
Sent: Saturday, March 19, 2016 10:51 PM
To: UCLALibrary/uclalibrary.github.io
Cc: Worsham, Doug
Subject: Re: [uclalibrary.github.io] Add hamburger menu to top right (#22)


hey Doug, I added a hamburger menu. What do you think of it? (ask a librarian isn't done yet, I plan to work on it next.)

-
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/UCLALibrary/uclalibrary.github.io/issues/22#issuecomment-198854664>

**Comment by anumat** [comment]
I've added it to all pages now!

**Comment by dmcwo** [comment]
Super. Closing! All the updates are looking great!!! Thanks for your work on this.
