### ISSUE TITLE
How to display 24/7?

### ISSUE THREAD

**Issue by dmcwo** [UCLALibrary/uclalibrary.github.io#25]
Hi Anumat,

Just curious about your thoughts on how to display when we're open 24/7:

Looks like the API gives us this:
https://www.evernote.com/l/AN8xgYyl_LxDw68n79Ni-XnDpSgZ51IsZTQB/image.png

Is there a way to get this to display "Open 24/7"?

Thanks!

**Comment by anumat** [comment]
yeah I was aware this was an issue. I'll have it display 'Open all day' instead of 24/7 because it might not be open all week haha.

**Comment by dmcwo** [comment]
Cool - thanks! But "open all day" might be confusing too (just because of "day") -- 24/7 inside the box for each day would maybe work?

**Comment by anumat** [comment]
Fixed this! It'll show `Open 24/7` for when the libraries are open all day.

**Comment by dmcwo** [comment]
Cool - thanks!
