### ISSUE TITLE
Buttons display "closed" while loading

### ISSUE THREAD

**Issue by dmcwo** [UCLALibrary/uclalibrary.github.io#30]
There seems to be a short bit of time while the page initially loads that the button displays "Closed" - then, once the page is loaded, it switches to whatever the real status is. I'm wondering can we have the default/loading text be something different (e.g., a "loading icon") -- interested in your thoughts and advice on the best approach.

**Comment by anumat** [comment]
I changed it to show 'Loading...' for now. I can work on making a loading gif show instead later on.

**Comment by dmcwo** [comment]
Cool. Sounds like a good solution!
