### ISSUE TITLE
Some overlap between arrow and open/closed icon on iPhone 5

### ISSUE THREAD

**Issue by dmcwo** [UCLALibrary/uclalibrary.github.io#35]
Got a report that there is some overlap between the arrow menu and the open/closed button on iPhone 5's - see:

https://www.evernote.com/l/AN-Joc7lVqxGXLungeVQxMsxtueu84Z2ct4B/image.png

**Comment by anumat** [comment]
the trouble is the site looks a little different on different phones. Not sure what we should do... fixing for iPhone 5 could mess it up for some other phone. Should I go ahead and fix for this one?

**Comment by dmcwo** [comment]
Hmmm. Would it help if "closed" were to the left of the arrow instead of under it?

**Comment by anumat** [comment]
with that we'll have the issue of some of the longer library names not fitting :(

**Comment by dmcwo** [comment]
Hmmm. That's true. What do you think is best? Do we need the arrows? Could the arrows follow the library name? Other solutions that might help make sure we don't have overlap issues?

**Comment by anumat** [comment]
hey Doug, I completely reorganized how elements were positioned internally. I think the issue is now fixed! Let me know if you see errors.

**Comment by dmcwo** [comment]
Tested w/ Chrome developer tools on standard set of devices. Seems to work!! Thanks!!

**Comment by anumat** [comment]
👍
