### ISSUE TITLE
White space on Galaxy Note 3

### ISSUE THREAD

**Issue by dmcwo** [UCLALibrary/uclalibrary.github.io#38]
![galaxy note 3](https://cloud.githubusercontent.com/assets/11355903/14256891/db949834-fa4f-11e5-9412-b21006a94b26.png)

Not sure what is going on here. My emulator doesn't show this, but the actual phone does....

**Comment by anumat** [comment]
huh, this is extremely strange... not really sure what to do about this

did you refresh to see if this shows up each time you load the page? could be a one off rendering error, or it could just be that the browser is really old.

what do you recommend?

**Comment by dmcwo** [comment]
Just learned that it works on Chrome on this phone, but not in an app called "Internet" --- strange ... maybe that is a Samsung specific app?

**Comment by anumat** [comment]
I suspect it's an outdated browser. I think we're fine since most new Android phones ship with Chrome.
